{% set name = "semi-ate-common" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-common-{{ version }}.tar.gz
  sha256: 320e882663bb55dbf87f50b75e99d5667a5319737dd88df58a5f92e3984b8d50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - ate_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-common/
  summary: Common package of ATE Projects
  license: GPL-2.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
