{% set name = "semi-ate-common" %}
{% set version = "1.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 224fcddb7cd7dc383fa33a81815f7c92b8d77280f23b37caeb1653d872d7170c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ate_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/semi-ate-common/
  summary: Common package of ATE Projects
  license: GPL-2.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
