{% set name = "semi-ate-common" %}
{% set version = "1.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semi-ate-common-{{ version }}.tar.gz
  sha256: 3f32bc23672fa4d1b27af6b4d26c8eeec7017a64283e1dbf24ad969e698c5ee5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ate_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/semi-ate-common/
  summary: Common package of ATE Projects
  license: GPL-2.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
